name: thermal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - flirimageextractor==1.5.3
    - opencv-contrib-python==4.5.1.48
    - pip install itk==5.3.0
    - pip install SimpleITK==2.2.1
    
